# Generated by Django 3.1.1 on 2020-10-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201008_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.post'),
            preserve_default=False,
        ),
    ]
