# Generated by Django 3.1.1 on 2020-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201008_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_id',
            field=models.ManyToManyField(blank=True, related_name='post_id', to='network.Comments'),
        ),
    ]
